### ISSUE TITLE
Backward navigation from all pages

### ISSUE THREAD

**Issue by tavro** [tavro/WorldHistoryTimeline#3]
Make it possible to navigate backwards on the timeline when you've entered a new century/decade/year.
This is very useful if you for example enter a specific year from a search engine.

**Comment by seabeePraveen** [comment]
i will solve this issue please assign this issue to me

**Comment by tavro** [comment]
go ahead! :-)

**Comment by seabeePraveen** [comment]
thank you

**Comment by seabeePraveen** [comment]
@tavro could u please share some screenshots describing the issue so i can get better understanding

**Comment by tavro** [comment]
a simple \<a\>-tag with content 'go back' would do fine.

there are no concept screenshots, sorry.

**Comment by seabeePraveen** [comment]
okay thank you for the information and i would try to complete this task by today!

**Comment by tavro** [comment]
however, this seems to be already implemented. thank you anyways!
